module.exports = {
  title: "New Makersaurus Project",
  tagline: "This code for this site was generated by Makersaurus",
  url: "https://example.h2o.ai",
  baseUrl: "/",
  projectName: "new-makersaurus-project", // Usually your repo name
  feedbackAssignee: "5675sp", // Should be a github username
  dependencies: {
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.5",
    "@mui/material": "^5.15.17",
    "react-player": "^2.16.0",
    "@docusaurus/theme-mermaid": "3.6.3",
  },
};
